map_update_interval: 20 #default 2.0
maxUrange: 6.0    #default 3.0
sigma: 0.05
kernelSize: 1
lstep: 0.05
astep: 0.05
iterations: 5
lsigma: 0.075
ogain: 3.0
lskip: 0
minimumScore: 1000 #default 50
srr: 0.01 #default 0.1
srt: 0.02 #default 0.2
str: 0.01 #default 0.1
stt: 0.02 #default 0.2
linearUpdate: 0.5    #defualt 1.0
angularUpdate: 0.2
temporalUpdate: 0.5
resampleThreshold: 0.5
particles: 100   #default 100
xmin: -50.0 #default -10
ymin: -50.0 #default -10
xmax: 50.0 #default 10
ymax: 50.0 #default 10
delta: 0.05 #default 0.05
llsamplerange: 0.01 #default 0.01
llsamplestep: 0.01 #default 0.01
lasamplerange: 0.005 #default 0.005
lasamplestep: 0.005 #default 0.005
